default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL', 10) %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>
  username: <%= ENV.fetch('POSTGRES_USER', 'cip') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'cip') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'cip_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB_TEST', 'cip_test') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'cip_production') %>
