source 'https://rubygems.org'

ruby '3.3.0'

gem 'rails', '~> 8.0.0'
gem 'puma', '~> 6.4'
gem 'pg', '~> 1.5'
gem 'bootsnap', require: false
gem 'rack-cors'

gem 'bunny', '~> 2.22'

gem 'redis', '~> 5.2'
gem 'connection_pool', '~> 2.4'

gem 'aws-sdk-s3', '~> 1.150'

gem 'aasm', '~> 5.5'

gem 'kaminari', '~> 1.2'
gem 'ransack', '~> 4.2'

gem 'jbuilder'

gem 'prometheus-client', '~> 4.2'

gem 'oj'
gem 'ulid-ruby', require: 'ulid'

gem 'dotenv-rails'

group :development, :test do
  gem 'rspec-rails', '~> 7.0'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :development do
  gem 'listen'
end
